### ISSUE TITLE
Loading schema from file system doesn't work on Windows

### ISSUE THREAD

**Issue by ralfhandl** [jdesrosiers/hyperjump-browser#4]
### Problem

Trying to load a schema from a relative location in the file system fails on Windows:

~~~js
const validateOpenApi = await validate("./schemas/v3.1/schema.json");
~~~

results in 

~~~
RetrievalError: Unable to load resource 'file:///C:/git/OpenAPI-Specification/schemas/v3.1/schema.json'.
 ❯ get node_modules/@hyperjump/browser/lib/browser/browser.js:29:13
 ❯ getSchema node_modules/@hyperjump/json-schema/lib/schema.js:31:18
 ❯ Module.validate node_modules/@hyperjump/json-schema/lib/core.js:21:18
 ❯ tests/v3.1/examples.test.js:14:25
~~~

### How to reproduce

~~~pwsh
git clone https://github.com/OAI/OpenAPI-Specification
cd OpenAPI-Specification
npm i
npm t
~~~

### Workaround

Fetching the schema from the file system and registering it works:

~~~js
registerSchema(JSON.parse(readFileSync("./schemas/v3.1/schema.json","utf8")),"http://localhost/schema");
const validateOpenApi = await validate("http://localhost/schema");
~~~

This is rather clumsy and not the documented [preferred way to work with file-based schemas on the server](https://github.com/hyperjump-io/json-schema?tab=readme-ov-file#usage).

**Comment by jdesrosiers** [comment]
This should be fixed now. I also took the opportunity to add automation for running test on windows, so hopefully going forward windows-specific bugs will be caught earlier.

Please update your dependencies and let me know if you have any more problems. The version of `@hyperjump/browser` should be 1.1.6.

**Comment by ralfhandl** [comment]
@jdesrosiers Works like a charm now, thanks!
